name: Build and publish storybook

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  storybook:
    name: Create storybook build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up backend environment
        uses: maykinmedia/setup-django-backend@v1.1.1
        with:
          apt-packages: 'libxml2-dev libxmlsec1-dev libxmlsec1-openssl gdal-bin'
          python-version: '3.10'
          optimize-postgres: 'no'
          setup-node: 'yes'
          npm-ci-flags: '--legacy-peer-deps'

      - name: Build Storybook docs
        run: |
          python src/manage.py collectstatic --noinput
          npm run build-storybook
        env:
          DJANGO_SETTINGS_MODULE: openforms.conf.ci
          SB_BASE_URL: '/open-forms'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./storybook-static

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Allow one concurrent deployment
    concurrency:
      group: "pages"
      cancel-in-progress: true

    runs-on: ubuntu-latest
    if: github.event_name == 'push'  # Exclude PRs
    needs: storybook
    steps:
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v1
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
